# Generated by Django 4.2.5 on 2023-10-18 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="TITLE", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
